import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# PTCG Agent: Discovery & Parser v2\n",
    "Run this notebook in your Kaggle environment to discover the true API and test the parser."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Discovery Cell\n",
    "This cell probes the `cg` engine directly. Please run it and copy the output back."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "import inspect\n",
    "\n",
    "print(\"🔍 Starting PTCG Engine Discovery...\")\n",
    "\n",
    "engine_path = \"/kaggle/input/competitions/pokemon-tcg-ai-battle/ptcg_engine\"\n",
    "sample_sub_path = \"/kaggle/input/competitions/pokemon-tcg-ai-battle/sample_submission/sample_submission\"\n",
    "\n",
    "if engine_path not in sys.path:\n",
    "    sys.path.insert(0, engine_path)\n",
    "if sample_sub_path not in sys.path:\n",
    "    sys.path.insert(0, sample_sub_path)\n",
    "\n",
    "try:\n",
    "    import cg\n",
    "    import cg.api\n",
    "    print(f\"✅ Successfully imported 'cg' from: {cg.__file__}\")\n",
    "except ImportError as e:\n",
    "    print(f\"❌ Failed to import 'cg': {e}\")\n",
    "    print(\"Checking directories:\")\n",
    "    os.system(f\"ls -la {sample_sub_path}\")\n",
    "\n",
    "if 'cg' in sys.modules:\n",
    "    print(\"\\n\" + \"=\"*50)\n",
    "    print(\"GROUND TRUTH: cg.api ENUMS\")\n",
    "    print(\"=\"*50)\n",
    "\n",
    "    classes_to_inspect = []\n",
    "    for name in dir(cg.api):\n",
    "        if name.startswith(\"_\"): continue\n",
    "        obj = getattr(cg.api, name)\n",
    "        if isinstance(obj, type):\n",
    "            classes_to_inspect.append((name, obj))\n",
    "\n",
    "    for name, obj in classes_to_inspect:\n",
    "        if hasattr(obj, '__members__'):\n",
    "            members = list(obj.__members__.keys())\n",
    "            print(f\"\\nEnum: {name} ({len(members)} members)\")\n",
    "            for m in members:\n",
    "                val = obj.__members__[m].value\n",
    "                print(f\"  - {m} = '{val}'\")\n",
    "\n",
    "    print(\"\\n\" + \"=\"*50)\n",
    "    print(\"GROUND TRUTH: cg.api DATACLASSES & FIELDS\")\n",
    "    print(\"=\"*50)\n",
    "\n",
    "    for name, obj in classes_to_inspect:\n",
    "        if not hasattr(obj, '__members__'):\n",
    "            print(f\"\\nClass: {name}\")\n",
    "            if hasattr(obj, '__annotations__'):\n",
    "                for field, f_type in obj.__annotations__.items():\n",
    "                    print(f\"  - {field}: {f_type}\")\n",
    "            else:\n",
    "                try:\n",
    "                    sig = inspect.signature(obj.__init__)\n",
    "                    print(f\"  - __init__ params: {list(sig.parameters.keys())}\")\n",
    "                except:\n",
    "                    print(\"  - (No type annotations or inspectable init found)\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Observation Parser (v2 with Fixes)\n",
    "This is the parser rebuilt from API docs with the 3 Blocker fixes and 5 Warning fixes applied."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from dataclasses import dataclass, field\n",
    "from typing import Any, Dict, List, Optional, Tuple\n",
    "from enum import Enum\n",
    "\n",
    "# ==========================================\n",
    "# ENUMS (Fixed with missing fields)\n",
    "# ==========================================\n",
    "class OptionType(Enum):\n",
    "    YES = \"YES\"\n",
    "    NO = \"NO\"\n",
    "    CARD = \"CARD\"\n",
    "    NUMBER = \"NUMBER\"\n",
    "    END = \"END\"\n",
    "    PLAY = \"PLAY\"\n",
    "    ATTACK = \"ATTACK\"\n",
    "    RETREAT = \"RETREAT\"\n",
    "    EVOLVE = \"EVOLVE\"\n",
    "    SKILL = \"SKILL\"\n",
    "    USE_POWER = \"USE_POWER\"  # [FIX P0] Added for abilities\n",
    "\n",
    "class SelectType(Enum):\n",
    "    MAIN = \"MAIN\"\n",
    "    CARD = \"CARD\"\n",
    "    ATTACHED_CARD = \"ATTACHED_CARD\"\n",
    "    CARD_OR_ATTACHED_CARD = \"CARD_OR_ATTACHED_CARD\"\n",
    "    ENERGY = \"ENERGY\"\n",
    "    SKILL = \"SKILL\"\n",
    "    ATTACK = \"ATTACK\"\n",
    "    EVOLVE = \"EVOLVE\"\n",
    "    COUNT = \"COUNT\"\n",
    "    YES_NO = \"YES_NO\"\n",
    "    SPECIAL_CONDITION = \"SPECIAL_CONDITION\"\n",
    "    POKEMON = \"POKEMON\"  # [FIX P0] Missing type\n",
    "    SELECT = \"SELECT\"    # [FIX P0] Missing type\n",
    "    ABILITY = \"ABILITY\"  # [FIX P0] Missing type\n",
    "\n",
    "class AreaType(Enum):\n",
    "    DECK = \"DECK\"\n",
    "    HAND = \"HAND\"\n",
    "    DISCARD = \"DISCARD\"\n",
    "    ACTIVE = \"ACTIVE\"\n",
    "    BENCH = \"BENCH\"\n",
    "    PRIZE = \"PRIZE\"\n",
    "    STADIUM = \"STADIUM\"\n",
    "    ENERGY = \"ENERGY\"\n",
    "    TOOL = \"TOOL\"\n",
    "    PRE_EVOLUTION = \"PRE_EVOLUTION\"\n",
    "    PLAYER = \"PLAYER\"\n",
    "    LOOKING = \"LOOKING\"\n",
    "\n",
    "# ==========================================\n",
    "# PARSED DATA STRUCTURES\n",
    "# ==========================================\n",
    "@dataclass\n",
    "class PokemonState:\n",
    "    card_id: int = 0\n",
    "    serial: int = 0\n",
    "    hp: int = 0\n",
    "    max_hp: int = 0\n",
    "    energies: List[int] = field(default_factory=list)\n",
    "    energy_cards: List[int] = field(default_factory=list)\n",
    "    tools: List[int] = field(default_factory=list)\n",
    "    pre_evolution: List[Any] = field(default_factory=list)\n",
    "    appear_this_turn: bool = False\n",
    "\n",
    "@dataclass\n",
    "class ParsedPlayerState:\n",
    "    active: List[PokemonState] = field(default_factory=list)\n",
    "    bench: List[PokemonState] = field(default_factory=list)\n",
    "    hand: List[int] = field(default_factory=list)\n",
    "    discard: List[PokemonState] = field(default_factory=list) # [FIX P1] Typed properly\n",
    "    prize_count: int = 6 # [FIX P0] Fixed bug where prize was a list of objects\n",
    "    hand_count: int = 0\n",
    "    deck_count: int = 0\n",
    "    bench_max: int = 5\n",
    "    poisoned: bool = False\n",
    "    burned: bool = False\n",
    "    asleep: bool = False\n",
    "    paralyzed: bool = False\n",
    "    confused: bool = False\n",
    "\n",
    "@dataclass\n",
    "class ParsedOption:\n",
    "    list_position: int = 0\n",
    "    option_type: Optional[OptionType] = None # [FIX P1] Strongly typed enum\n",
    "    area: Optional[AreaType] = None # [FIX P1] Strongly typed enum\n",
    "    index: int = 0\n",
    "    player_index: int = 0\n",
    "    number: int = 0\n",
    "\n",
    "@dataclass\n",
    "class ParsedSelectData:\n",
    "    select_type: str = \"\"\n",
    "    context: str = \"\"\n",
    "    options: List[ParsedOption] = field(default_factory=list)\n",
    "    min_count: int = 1\n",
    "    max_count: int = 1\n",
    "    deck: List[Any] = field(default_factory=list)\n",
    "\n",
    "@dataclass\n",
    "class ParsedObservation:\n",
    "    your_index: int = 0\n",
    "    my_state: ParsedPlayerState = field(default_factory=ParsedPlayerState)\n",
    "    opp_state: ParsedPlayerState = field(default_factory=ParsedPlayerState)\n",
    "    select: Optional[ParsedSelectData] = None\n",
    "    is_setup_phase: bool = False\n",
    "    logs: List[Any] = field(default_factory=list)\n",
    "\n",
    "# ==========================================\n",
    "# SAFE EXTRACTION UTILS\n",
    "# ==========================================\n",
    "def _safe_get(obj: Any, key: str, default: Any = None) -> Any:\n",
    "    if obj is None:\n",
    "        return default\n",
    "    if isinstance(obj, dict):\n",
    "        return obj.get(key, default)\n",
    "    return getattr(obj, key, default)\n",
    "\n",
    "def _safe_int(val: Any, default: int = 0) -> int:\n",
    "    if val is None:\n",
    "        return default\n",
    "    try:\n",
    "        return int(val)\n",
    "    except (ValueError, TypeError):\n",
    "        return default\n",
    "\n",
    "def _safe_bool(val: Any, default: bool = False) -> bool:\n",
    "    if val is None:\n",
    "        return default\n",
    "    try:\n",
    "        return bool(val)\n",
    "    except (ValueError, TypeError):\n",
    "        return default\n",
    "\n",
    "def _enum_to_string(val: Any) -> str: # [FIX P1] Robust enum string extraction\n",
    "    if hasattr(val, 'name'): return val.name\n",
    "    if hasattr(val, 'value'): return str(val.value)\n",
    "    return str(val)\n",
    "\n",
    "# ==========================================\n",
    "# PARSING FUNCTIONS\n",
    "# ==========================================\n",
    "def _parse_pokemon(raw: Any) -> PokemonState:\n",
    "    if raw is None:\n",
    "        return PokemonState()\n",
    "    poke = PokemonState()\n",
    "    poke.card_id = _safe_int(_safe_get(raw, 'id', _safe_get(raw, 'cardId', 0)))\n",
    "    poke.serial = _safe_int(_safe_get(raw, 'serial', 0))\n",
    "    poke.hp = _safe_int(_safe_get(raw, 'hp', 0))\n",
    "    poke.max_hp = _safe_int(_safe_get(raw, 'maxHp', _safe_get(raw, 'max_hp', 0)))\n",
    "    poke.appear_this_turn = _safe_bool(_safe_get(raw, 'appearThisTurn', False))\n",
    "    return poke\n",
    "\n",
    "def _parse_pokemon_list(raw_list: Any) -> List[PokemonState]:\n",
    "    if not raw_list or not isinstance(raw_list, (list, tuple)):\n",
    "        return []\n",
    "    return [_parse_pokemon(p) for p in raw_list if p is not None]\n",
    "\n",
    "def _parse_player_state(raw_player: Any) -> ParsedPlayerState:\n",
    "    if raw_player is None:\n",
    "        return ParsedPlayerState()\n",
    "    state = ParsedPlayerState()\n",
    "    raw_active = _safe_get(raw_player, 'active', [])\n",
    "    state.active = _parse_pokemon_list(raw_active if isinstance(raw_active, (list, tuple)) else [raw_active] if raw_active else [])\n",
    "    state.bench = _parse_pokemon_list(_safe_get(raw_player, 'bench', []))\n",
    "    raw_hand = _safe_get(raw_player, 'hand', None)\n",
    "    if raw_hand is not None and isinstance(raw_hand, (list, tuple)):\n",
    "        state.hand = [_safe_int(_safe_get(c, 'id', _safe_get(c, 'cardId', c))) for c in raw_hand]\n",
    "    else:\n",
    "        state.hand = []\n",
    "    state.hand_count = _safe_int(_safe_get(raw_player, 'handCount', len(state.hand)))\n",
    "    state.deck_count = _safe_int(_safe_get(raw_player, 'deckCount', 0))\n",
    "    \n",
    "    # [FIX P1] Parse discard correctly as PokemonState list\n",
    "    state.discard = _parse_pokemon_list(_safe_get(raw_player, 'discard', []))\n",
    "    \n",
    "    # [FIX P0] Fix prize counting logic\n",
    "    raw_prize = _safe_get(raw_player, 'prize', [])\n",
    "    state.prize_count = _safe_int(_safe_get(raw_player, 'prizeCount', len(raw_prize) if isinstance(raw_prize, (list, tuple)) else 0))\n",
    "    if state.prize_count == 0 and len(raw_prize) > 0:\n",
    "        state.prize_count = len(raw_prize)\n",
    "        \n",
    "    state.bench_max = _safe_int(_safe_get(raw_player, 'benchMax', 5), 5)\n",
    "    state.poisoned = _safe_bool(_safe_get(raw_player, 'poisoned', False))\n",
    "    state.burned = _safe_bool(_safe_get(raw_player, 'burned', False))\n",
    "    state.asleep = _safe_bool(_safe_get(raw_player, 'asleep', False))\n",
    "    state.paralyzed = _safe_bool(_safe_get(raw_player, 'paralyzed', False))\n",
    "    state.confused = _safe_bool(_safe_get(raw_player, 'confused', False))\n",
    "    return state\n",
    "\n",
    "def _parse_option(raw_option: Any, list_position: int) -> ParsedOption:\n",
    "    if raw_option is None:\n",
    "        return ParsedOption(list_position=list_position)\n",
    "    opt = ParsedOption()\n",
    "    opt.list_position = list_position\n",
    "    \n",
    "    # [FIX P1] Convert strings to explicit enums safely\n",
    "    opt_type_str = _enum_to_string(_safe_get(raw_option, 'type', ''))\n",
    "    try: opt.option_type = OptionType(opt_type_str)\n",
    "    except ValueError: opt.option_type = None\n",
    "        \n",
    "    area_str = _enum_to_string(_safe_get(raw_option, 'area', ''))\n",
    "    try: opt.area = AreaType(area_str)\n",
    "    except ValueError: opt.area = None\n",
    "        \n",
    "    opt.index = _safe_int(_safe_get(raw_option, 'index', 0))\n",
    "    opt.player_index = _safe_int(_safe_get(raw_option, 'playerIndex', 0))\n",
    "    opt.number = _safe_int(_safe_get(raw_option, 'number', 0))\n",
    "    return opt\n",
    "\n",
    "def _parse_select_data(raw_select: Any) -> Optional[ParsedSelectData]:\n",
    "    if raw_select is None:\n",
    "        return None\n",
    "    sel = ParsedSelectData()\n",
    "    sel.select_type = _enum_to_string(_safe_get(raw_select, 'type', ''))\n",
    "    sel.context = _enum_to_string(_safe_get(raw_select, 'context', ''))\n",
    "    \n",
    "    raw_options = _safe_get(raw_select, 'option', [])\n",
    "    if isinstance(raw_options, (list, tuple)):\n",
    "        sel.options = [_parse_option(o, i) for i, o in enumerate(raw_options)]\n",
    "        \n",
    "    sel.min_count = _safe_int(_safe_get(raw_select, 'minCount', 1), 1)\n",
    "    sel.max_count = _safe_int(_safe_get(raw_select, 'maxCount', 1), 1)\n",
    "    return sel\n",
    "\n",
    "def parse_observation(raw_obs: Any) -> ParsedObservation:\n",
    "    obs = ParsedObservation()\n",
    "    raw_current = _safe_get(raw_obs, 'current', None)\n",
    "    if raw_current is not None:\n",
    "        obs.your_index = _safe_int(_safe_get(raw_current, 'yourIndex', 0))\n",
    "        raw_players = _safe_get(raw_current, 'players', [])\n",
    "        if isinstance(raw_players, (list, tuple)) and len(raw_players) > 0:\n",
    "            obs.my_state = _parse_player_state(raw_players[obs.your_index] if len(raw_players) > obs.your_index else None)\n",
    "            opp_idx = 1 - obs.your_index\n",
    "            obs.opp_state = _parse_player_state(raw_players[opp_idx] if len(raw_players) > opp_idx else None)\n",
    "        \n",
    "        # [FIX P1] Explicit phase checking for setup phase\n",
    "        phase_str = _enum_to_string(_safe_get(raw_current, 'phase', ''))\n",
    "        if phase_str == \"SETUP\":\n",
    "            obs.is_setup_phase = True\n",
    "            \n",
    "    obs.select = _parse_select_data(_safe_get(raw_obs, 'select', None))\n",
    "    if obs.select is None:\n",
    "        obs.is_setup_phase = True\n",
    "        \n",
    "    return obs\n",
    "\n",
    "print(\"✅ Parsed v2 loaded into memory. You can now run `parse_observation(obs)` on a real observation to test it!\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("notebooks/kaggle_discovery_and_parser.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)
